#!/usr/bin/env python3
"""
Import dr-acervo/blog-posts into D1 and generate xAI TTS podcast audio.

Usage:
  python3 scripts/publish-acervo-posts.py              # import + tts missing
  python3 scripts/publish-acervo-posts.py --skip-tts   # D1 only
  python3 scripts/publish-acervo-posts.py --tts-only   # audio only
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.request
from datetime import date, timedelta
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ACERVO = Path("/Users/gustavomendesesilva/Developer/dr-acervo/blog-posts")
AUDIO_DIR = ROOT / "public" / "blog-audio"
SQL_OUT = ROOT / "scripts" / "_import-posts.sql"

# Editorial calendar 2026: ~every 6 days from mid-March through late July.
DATE_START = date(2026, 3, 18)
INTERVAL_DAYS = 6

AUTHOR = "Dr. Gustavo Mendes e Silva"
VOICE_ID = "leo"  # male multilingual — clinical tone
LANGUAGE = "pt-BR"
SPEED = 0.95

# Keep conceito; upsert drafts (including existing desarme-precoce / disruptura bodies)
SKIP_SLUGS = {"conceito-de-doenca-mental"}


def parse_frontmatter(text: str) -> tuple[dict, str]:
    m = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
    if not m:
        raise ValueError("missing frontmatter")
    fm: dict = {}
    raw = m.group(1)
    # simple YAML subset
    key = None
    list_mode = False
    for line in raw.splitlines():
        if re.match(r"^\s*-\s+", line) and list_mode and key:
            fm.setdefault(key, []).append(re.sub(r"^\s*-\s+", "", line).strip().strip('"').strip("'"))
            continue
        list_mode = False
        if ":" not in line:
            continue
        k, v = line.split(":", 1)
        k = k.strip()
        v = v.strip()
        if v == "":
            key = k
            list_mode = True
            fm[k] = []
            continue
        key = k
        if v.startswith("[") and v.endswith("]"):
            try:
                fm[k] = json.loads(v.replace("'", '"'))
            except Exception:
                fm[k] = [x.strip().strip('"').strip("'") for x in v[1:-1].split(",") if x.strip()]
        else:
            fm[k] = v.strip('"').strip("'")
    body = m.group(2).strip()
    # drop duplicate H1 if present
    body = re.sub(r"^#\s+.+\n+", "", body, count=1)
    return fm, body


def strip_md_for_tts(md: str) -> str:
    text = md
    text = re.sub(r"```[\s\S]*?```", " ", text)
    text = re.sub(r"`([^`]+)`", r"\1", text)
    text = re.sub(r"!\[([^\]]*)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", text)
    text = re.sub(r"^#{1,6}\s+", "", text, flags=re.M)
    text = re.sub(r"[*_~>#]", " ", text)
    text = re.sub(r"\|", " ", text)
    text = re.sub(r"\n{2,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    # Soft pause markers for sections
    text = text.replace("\n\n", ". ")
    text = re.sub(r"\s+", " ", text).strip()
    # TTS limit 15000
    if len(text) > 14500:
        text = text[:14500].rsplit(" ", 1)[0] + "."
    return text


def collect_posts() -> list[dict]:
    files = sorted(ACERVO.glob("**/*.md"))
    files = [f for f in files if f.name != "README.md"]
    posts = []
    for path in files:
        fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        slug = fm.get("slug")
        if not slug or slug in SKIP_SLUGS:
            continue
        series = fm.get("series") or ""
        # series from folder if missing
        if not series:
            folder = path.parent.name
            series = re.sub(r"^\d+-", "", folder).replace("-", " ").title()
        keywords = fm.get("keywords") or []
        if isinstance(keywords, str):
            keywords = [keywords]
        posts.append(
            {
                "slug": slug,
                "title": fm.get("title") or slug,
                "subtitle": fm.get("subtitle") or "",
                "author": fm.get("author") or AUTHOR,
                "read_time": fm.get("read_time") or "8 min",
                "excerpt": fm.get("excerpt") or "",
                "keywords": keywords,
                "body_md": body,
                "series": series,
                "path": str(path),
            }
        )
    # chronological assignment in folder/file order (already sorted)
    d = DATE_START
    for p in posts:
        p["date"] = d.isoformat()
        d += timedelta(days=INTERVAL_DAYS)
    return posts


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def build_sql(posts: list[dict]) -> str:
    now = int(time.time())
    lines = ["-- Auto-generated by publish-acervo-posts.py", "BEGIN TRANSACTION;"]
    for p in posts:
        audio = f"/blog-audio/{p['slug']}.mp3"
        kw = json.dumps(p["keywords"], ensure_ascii=False)
        lines.append(
            f"""INSERT OR REPLACE INTO posts (
  slug, title, subtitle, author, date, read_time, excerpt, keywords,
  body_md, header_image, scroll_style, status, original_key, screenshot_key,
  created_at, updated_at, series, audio_url
) VALUES (
  '{sql_escape(p["slug"])}',
  '{sql_escape(p["title"])}',
  '{sql_escape(p["subtitle"])}',
  '{sql_escape(p["author"])}',
  '{p["date"]}',
  '{sql_escape(p["read_time"])}',
  '{sql_escape(p["excerpt"])}',
  '{sql_escape(kw)}',
  '{sql_escape(p["body_md"])}',
  NULL,
  'section-overlay',
  'published',
  NULL,
  NULL,
  {now},
  {now},
  '{sql_escape(p["series"])}',
  '{audio}'
);"""
        )
    lines.append("COMMIT;")
    return "\n".join(lines)


def wrangler_d1_file(sql_path: Path) -> None:
    # Split into individual statements for wrangler reliability
    sql = sql_path.read_text(encoding="utf-8")
    # Extract INSERT statements
    inserts = re.findall(r"INSERT OR REPLACE INTO posts[\s\S]*?\);", sql)
    print(f"Executing {len(inserts)} INSERT statements…")
    for i, stmt in enumerate(inserts, 1):
        tmp = Path(f"/tmp/post-insert-{i:02d}.sql")
        tmp.write_text(stmt + "\n", encoding="utf-8")
        r = subprocess.run(
            ["npx", "wrangler", "d1", "execute", "dr-blog", "--remote", "--file", str(tmp)],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if r.returncode != 0:
            print(r.stdout)
            print(r.stderr)
            raise SystemExit(f"D1 insert failed at {i}")
        print(f"  [{i}/{len(inserts)}] ok")


def tts_generate(text: str, out_path: Path) -> None:
    key = os.environ.get("XAI_API_KEY")
    if not key:
        raise SystemExit("XAI_API_KEY missing")
    payload = {
        "text": text,
        "voice_id": VOICE_ID,
        "language": LANGUAGE,
        "speed": SPEED,
        "output_format": {"codec": "mp3", "sample_rate": 24000, "bit_rate": 128000},
    }
    req = urllib.request.Request(
        "https://api.x.ai/v1/tts",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=300) as resp:
            data = resp.read()
    except urllib.error.HTTPError as e:
        err = e.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"TTS HTTP {e.code}: {err}") from e
    if len(data) < 1000:
        raise RuntimeError(f"TTS response too small ({len(data)} bytes)")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(data)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--skip-tts", action="store_true")
    ap.add_argument("--tts-only", action="store_true")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    posts = collect_posts()
    if args.limit:
        posts = posts[: args.limit]
    print(f"Collected {len(posts)} posts")
    for p in posts:
        print(f"  {p['date']}  {p['slug']}  [{p['series']}]")

    if not args.tts_only:
        sql = build_sql(posts)
        SQL_OUT.write_text(sql, encoding="utf-8")
        print(f"Wrote {SQL_OUT}")
        wrangler_d1_file(SQL_OUT)
        print("D1 import done")

    if not args.skip_tts:
        AUDIO_DIR.mkdir(parents=True, exist_ok=True)
        for i, p in enumerate(posts, 1):
            out = AUDIO_DIR / f"{p['slug']}.mp3"
            if out.exists() and out.stat().st_size > 10_000:
                print(f"  [{i}/{len(posts)}] skip existing {out.name}")
                continue
            plain = strip_md_for_tts(p["body_md"])
            # Intro for podcast feel
            intro = f"{p['title']}. {p['subtitle']}. Por {p['author']}. " if p.get("subtitle") else f"{p['title']}. Por {p['author']}. "
            full = intro + plain
            print(f"  [{i}/{len(posts)}] TTS {p['slug']} ({len(full)} chars)…")
            tts_generate(full, out)
            print(f"       → {out.stat().st_size // 1024} KB")
            time.sleep(0.4)
        print("TTS done")

    print("OK")


if __name__ == "__main__":
    main()
